BASE_SYSTEM_TEXT = """
You will receive the code piece by piece.
For each new snippet, you must:
Explain in detail what every function, class, or block of logic does.
Parse and describe the structure, purpose, and functionality of the snippet.
Connect this snippet to all previously received parts, preserving and using the accumulated context to understand the full logic of the project.
If behavior becomes clearer with the new piece, update or refine previous conclusions.
You should understand, that it is not full code, it is just part
Do NOT skip details; analyze everything that appears in the snippet.
"""

BASE_COMPRESS_TEXT = """
You will receive a large code snippet (up to ~10,000 characters).
Your task is to:
Extract the core idea and architecture of the code.
Preserve the logical flow and key details required to understand how the code works.
Identify and explain:
main components (functions, classes, modules),
critical logic paths,
data flow and interactions,
important conditions, side effects, and assumptions.
Remove repetition, boilerplate, and minor implementation details that do not affect understanding.
Compress the explanation into a final summary of no more than ~5,000 characters.
The final output must:
remain accurate,
keep the original meaning and intent,
allow a developer to understand the code without reading the full source.
Do not include raw code unless absolutely necessary.
Focus on meaning, logic, and structure, not syntax.
"""

BASE_PART_COMPLITE_TEXT = """You will receive:
A global description of the system, including its overall purpose, architecture, and core logic.
A specific code snippet that represents a part of this system.
Your task is to:
Write clear and structured documentation for the given code snippet.
dont make it too long around 2k symbols
Explain what this code does within the context of the entire system, not in isolation.
You should understand, that it is not full code, it is just part
near titles like ## title use a link <a name="title"></a>

Describe:
the responsibility of this component,
how it interacts with other parts of the system,
key functions, classes, and logic flows,
important assumptions, inputs, outputs, and side effects.
Use the global system description as the primary context to ensure correctness and consistency.
Do NOT restate the global description — focus only on documenting the current code fragment.
Write documentation that is suitable for developers who are new to this codebase.
Keep the documentation concise, precise, and technically accurate."""

BASE_INTRODACTION_CREATE_TEXT = """
Вот финальный, отточенный промпт на английском языке. Он заставляет модель работать как строгий технический архитектор: фильтровать 70% контента, оставляя только «ядро», и ни в коем случае не менять сгенерированные вами ссылки.
Final Prompt for ChatGPT
Role: Senior Technical Solutions Architect.
Task: Create a high-level, "50% density" Executive Navigation Tree from a provided list of Markdown links.
Input Data: A list of pre-formatted links: [Header Text](#generated-anchor).
Strict Constraints:
The 30% Rule: Analyze the entire list and identify only the most critical architectural components. Discard approximately 70% of the items (minor files, repetitive utility scripts, FAQs, and sub-sections like "Overview" or "Summary").
Deterministic Links (No Hallucinations): You MUST NOT change or "clean up" the (#anchor) part of the links. Even if they look long or strange, keep them exactly as provided. They are generated by a script and any change will break the navigation.
Logical Grouping: Organize the selected 50% into a clean, hierarchical tree using nested bullet points. Group files by their functional module (e.g., Authorization, Currency, Game Core).

Visual Requirements:
Use a professional, scannable structure.
Add minimal emojis for clarity (e.g., 📂 for modules, ⚙️ for services, 📄 for key files).
The link text should remain descriptive but the anchor must stay identical to the input.
"""

BASE_INTRO_CREATE = """
Act as a professional Technical Writer. I will provide you with a general description of my code and its operating principles. 

Your task is to generate a comprehensive project overview that includes the following sections:

1. **Project Title**: A concise and clear name for the project.
2. **Project Goal**: A high-level explanation of what this software aims to achieve and what problem it solves.
3. **Core Logic & Principles**: A detailed but accessible explanation of how the code works, the logic behind it, and the main technologies/algorithms used.
4. **Key Features**: A bulleted list of the main functionalities.
5. **How to Run**: Step-by-step instructions on how to set up the environment and execute the code.
6. **Dependencies**: List any necessary libraries or tools required to run the project.

Please use professional, clear, and "clean" English. 
"""

def get_BASE_COMPRESS_TEXT(start, power):
    return f"""
You will receive a large code snippet (up to ~{start} characters).
Your task is to:
Extract the core idea and architecture of the code.
Preserve the logical flow and key details required to understand how the code works.
Identify and explain:
main components (functions, classes, modules),
critical logic paths,
data flow and interactions,
important conditions, side effects, and assumptions.
Remove repetition, boilerplate, and minor implementation details that do not affect understanding.
Compress the explanation into a final summary of no more than ~{int(start / power)} characters.
The final output must:
remain accurate,
keep the original meaning and intent,
allow a developer to understand the code without reading the full source.
Do not include raw code unless absolutely necessary.
Focus on meaning, logic, and structure, not syntax.
Add info how use that code
"""

import os
from dotenv import load_dotenv

load_dotenv() 
API_KEY = os.getenv("API_KEY")

MODELS_NAME = ["openai/gpt-oss-120b",  "llama-3.3-70b-versatile",  "openai/gpt-oss-safeguard-20b"]